name       : github-cli
version    : 2.14.4
release    : 16
source     :
    - https://github.com/cli/cli/archive/refs/tags/v2.14.4.tar.gz : be93380e5a7f2822a1bfeff80f23231ee72ca297b9bc05bba0a1c688f9f53ccf
license    : MIT
component  : system.utils
summary    : GitHub’s official command line tool
description: |
    github-cli is a tool that allows for GitHub concepts such as pull requests, issues, and gists to be used on the command line.
networking : yes
builddeps  :
    - git
    - golang
rundeps    :
    - git
build      : |
    make GH_VERSION="v$version" bin/gh manpages
    bin/gh completion -s bash | install -Dm644 /dev/stdin share/bash-completion/completions/gh
    bin/gh completion -s zsh | install -Dm644 /dev/stdin share/zsh/site-functions/_gh
    bin/gh completion -s fish | install -Dm644 /dev/stdin share/fish/vendor_completions.d/gh.fish
install    : |
    install -Dm00755 $workdir/bin/gh $installdir/usr/bin/gh
    cp -r $workdir/share/ $installdir/usr
