name       : github-cli
version    : 1.13.1
release    : 6
source     :
    - https://github.com/cli/cli/archive/refs/tags/v1.13.1.tar.gz : 1a19ab2bfdf265b5e2dcba53c3bd0b5a88f36eff4864dcc38865e33388b600c5
license    : MIT
component  : system.utils
summary    : GitHub’s official command line tool
description: |
    github-cli is a tool that allows for GitHub concepts such as pull requests, issues, and gists to be used on the command line.
networking : yes
builddeps  :
    - git
    - golang
rundeps    :
    - git
build      : |
    make bin/gh
    make manpages
    bin/gh completion -s bash | install -Dm644 /dev/stdin share/bash-completion/completions/gh
    bin/gh completion -s zsh | install -Dm644 /dev/stdin share/zsh/site-functions/_gh
    bin/gh completion -s fish | install -Dm644 /dev/stdin share/fish/vendor_completions.d/gh.fish
install    : |
    install -Dm00755 $workdir/bin/gh $installdir/usr/bin/gh
    cp -r $workdir/share/ $installdir/usr
