name       : github-cli
version    : 1.0.0
release    : 1
source     :
    - https://github.com/cli/cli/archive/v1.0.0.tar.gz : e3d1c341829f5b885dce9aa2bf4bc84db48072752250f6fdb2d62903caf07cfb
license    : MIT
component  : system.utils
summary    : GitHub’s official command line tool 
description: |
    github-cli is a tool that allows for GitHub concepts such as pull requests, issues, and gists to be used on the command line.
networking : yes
builddeps  : 
    - git
    - golang
rundeps    : 
    - git
build      : |
    make bin/gh
    make manpages
    bin/gh completion -s bash | install -Dm644 /dev/stdin share/bash-completion/completions/gh
    bin/gh completion -s zsh | install -Dm644 /dev/stdin share/zsh/site-functions/_gh
    bin/gh completion -s fish | install -Dm644 /dev/stdin share/fish/vendor_completions.d/gh.fish
install    : |
    install -Dm00755 $workdir/bin/gh $installdir/usr/bin/gh
    cp -r $workdir/share/ $installdir/usr
